version: "3.9"

services:
#  app:
#    networks:
#      - monopoly-backend
#    container_name: game
#    image: monopoly
#    build: .
#    depends_on:
#      - monopoly_db
#    ports:
#      - '8081:8080'

  phpmyadmin:
    networks:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      - PMA_ARBITRARY=1

  monopoly_db:
    networks:
      - db
    container_name: monopoly-db
    image: mysql
    volumes:
      - monopoly-db:/var/lib/mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monopoly
      MYSQL_PASSWORD: root
    ports:
      - '3310:3306'

networks:
  db:
    driver: bridge

volumes:
  phpmyadmin:
  monopoly-db:
