version: "3.9"

services:
  db:
    image: mysql
    volumes:
      - monopoly-db:/var/lib/mysql
    command: [ "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--max-allowed-packet=67108864" ]
    restart: always
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'monopoly'
      MYSQL_PASSWORD: 'root'
    ports:
      - '3310:3306'
    expose:
      - '3310'

  test_db:
    image: mysql
    volumes:
      - monopoly-test-db:/var/lib/mysql
    command: [ "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--max-allowed-packet=67108864" ]
    restart: always
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'monopoly_test'
      MYSQL_PASSWORD: 'root'
    ports:
      - '3320:3306'
    expose:
      - '3320'

volumes:
  monopoly-db: {}
  monopoly-test-db: {}
