version: "3.9"

services:
#  monopoly:
#    networks:
#      - db
#    container_name: monopoly
#    image: alialiev/monopoly
#    build: .
#    depends_on:
#      - monopoly_db
#      - test_db
#    ports:
#      - '8081:8080'
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker

  phpmyadmin:
    networks:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - '8085:80'
    environment:
      - PMA_ARBITRARY=1

  monopoly_db:
    networks:
      - db
    container_name: monopoly-db
    image: mysql
    volumes:
      - monopoly-db:/var/lib/mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monopoly
      MYSQL_PASSWORD: root
    ports:
      - '3310:3306'

  test_db:
    networks:
      - db
    container_name: monopoly-db-test
    image: mysql
    volumes:
      - monopoly-db-test:/var/lib/mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: monopoly_test
      MYSQL_PASSWORD: root
    ports:
      - '3320:3306'

networks:
  db:
    driver: bridge

volumes:
  phpmyadmin:
  monopoly-db:
#  monopoly-db-test:
