version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - monopoly-db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'monopoly'
      MYSQL_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'

volumes:
  monopoly-db: {}