name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
#      - name: Build the stack
#        run: docker-compose up -d
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
      - name: Build the docker-compose stack
        run: docker-compose -f "docker-compose.yml" up -d --build
      - name: build with maven
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
